apiVersion: apps/v1
kind: Deployment
metadata:
  name: moonshot-input
  labels:
    app: moonshot-input
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moonshot-input
  template:
    metadata:
      labels:
        app: moonshot-input
    spec:
      containers:
      - name: moonshot-input
        image: scr.io/moonshot-samples-input:latest
        volumeMounts:
        - mountPath: /app/Configuration
          name: config
      volumes:
      - name: config
        configMap:
          name: input-configuration
          items:
          - key: "config.tags"
            path: configuration.yml
          - key: "tags"
            path: tags-configuration.yml
